### ISSUE TITLE
queries not intended for the configured domain should be sent to next plugin in the server chain

### ISSUE THREAD

**Issue by celebdor** [cybertron/coredns-hello#1]
It should be possible to have a configuration for any domain that looked like the one in OCP [cluster-dns-operator](https://github.com/openshift/cluster-dns-operator/blob/master/assets/dns/configmap.yaml#L17) or this:

```
. {
    errors
    health
    mdns ostest.test.metalkube.org
    forward . /etc/resolv.conf {
        except ostest.test.metalkube.org
    }
    cache 30
    reload
}
```

Note that for that to happen and have mdns be given the query before forward is, we probably need to compile CoreDNS with the plugin and [plugin.cfg](https://github.com/coredns/coredns/blob/master/plugin.cfg) listing mdns before forward

**Comment by cybertron** [comment]
This is actually working already because of the except in the forward configuration. Even though mdns is at the bottom of the list the appropriate queries still fall through to it because forward ignores them.
